language: node_js
node_js: 
  - 'stable'

cache:
  dependencies:
    node_modules

script:
  - npm install
  - npm test
  - npm  build

deploy:
  provider: surge
  skip_cleanup: true
  domain: skillful-measure.surge.sh
  project: ./build/  


on:
  branch: master         